server:
  port: 8484
  servlet:
    context-path: /mmms
    session:
      timeout: 600m

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.13:3306/tao?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource

  #支持上传文件
  servlet:
    multipart:
      enabled: true
      max-file-size: 107374182400

  redis:
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        min-idle: 1
        max-idle: 100

  thymeleaf:
    suffix: .html
    content-type: text/html
    mode: HTML5
    encoding: UTF-8
    cache: false
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kido
  configuration:
    #表示当查出来是null的时候，也会返给map中，不会不显示该值
    call-setters-on-nulls: true
    #配置输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #mybatis默认是属性名和数据库字段名一一对应的，即数据库表列：user_name 实体类属性：user_name
    #但是java中一般使用驼峰命名 数据库表列：user_name 实体类属性：userName
    #在Springboot中，可以通过设置map-underscore-to-camel-case属性为true来开启驼峰功能。
    map-underscore-to-camel-case: true

  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

